package soccervio.back.entities;

public enum NotificationType {
    NEW_IVITATION,
    INVITATION_ACCEPTED,
    ACCEPTED_INVIT_INVITE,
    ACCEPTED_INVIT_PROP,
    RESPONSE_ANNONCE,
    NEW_RESERVATION,
    ANNULER_RESERVATION,
    PARTICIATION_REFUSE
}
